notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
python: 3.7
matrix:
  include:
  - python: 3.7
services: docker
addons:
  apt:
    update: true
    packages:
    - python3-setuptools
    - python3-pip
install: true
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip -V
- pip3 install --user --upgrade pip >/dev/null # pip3 -> pip
- pip install --user --upgrade httpie >/dev/null
- http --version --debug
- pip -V
- |
  if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
    mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
    curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  fi
  source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
- stop_any 80 5432 8080
jobs:
  include:
  - stage: test
    jdk: openjdk11
    name: spring-boot-2-2
    script: cd $TRAVIS_BUILD_DIR && ./mvnw -f spring-boot-2-2/
  - stage: test
    jdk: openjdk8
    name: mvn test
    script: cd $TRAVIS_BUILD_DIR && ./mvnw
  - stage: test
    jdk: openjdk11
    name: mvn test openjdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw
  - stage: test
    jdk: openjdk8
    name: ddd integration tests
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -pl ddd
    - java -jar $TRAVIS_BUILD_DIR/ddd/target/*.jar &
    - wait_for 8002
    - http :8002 name=test
    - http :8002 name=test
    - http :8002 name="test 2"
    - http :8002/statistics
    - stop_any 80 8002
  - stage: test
    jdk: openjdk11
    name: ddd integration tests openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f $TRAVIS_BUILD_DIR/ddd/pom.xml
    - java -jar $TRAVIS_BUILD_DIR/ddd/target/*.jar &
    - wait_for 8002
    - http :8002 name=test
    - http :8002 name=test
    - http :8002 name="test 2"
    - http :8002/statistics
    - stop_any 80 8002
  - stage: test
    jdk: openjdk8
    name: simple integration tests
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -pl :simple
    - java -jar $TRAVIS_BUILD_DIR/simple/target/*.jar &
    - wait_for 8001
    - http :8001
    - http :8001 name=test
    - http :8001/find-all
    - stop_any 80 8001
  - stage: test
    jdk: openjdk11
    name: simple integration tests openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -f simple/pom.xml
    - bash $TRAVIS_BUILD_DIR/simple/target/*.jar &
    - wait_for 8001
    - http :8001
    - http :8001 name=test
    - http :8001/find-all
    - stop_any 80 8001
  - stage: test
    jdk: openjdk8
    name: mvn versions:display-property-updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
  - stage: test
    jdk: openjdk11
    name: mvn versions:display-property-updates (openjdk11)
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
  - ~/.local/daggerok
  - ~/.docker
  - ~/.m2
  packages: true
  pip: true
